In [1]:
import numpy as np
print(np.arange(30))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [2]:
print(np.arange(30).dtype)

int32


In [3]:
print(np.arange(30).reshape(5,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [4]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
print(np.zeros((2,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
print(np.zeros((2,5)),int)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] <class 'int'>


In [18]:
print(np.zeros((2,5)).ndim)

2


In [20]:
print(np.zeros((2,5)).shape)

(2, 5)


In [24]:
print(np.random.random((2,5)))

[[0.23266177 0.27902194 0.77247108 0.41909325 0.68493721]
 [0.94399033 0.35400395 0.8476713  0.77239041 0.82717498]]


In [29]:
test_a=np.array([[1,2,3],[4,5,6]],float)

In [30]:
print(test_a+test_a)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]


In [31]:
print(test_a-test_a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [32]:
print(test_a.transpose())

[[1. 4.]
 [2. 5.]
 [3. 6.]]


In [33]:
print(test_a.T.dot(test_a))

[[17. 22. 27.]
 [22. 29. 36.]
 [27. 36. 45.]]


In [34]:
print(test_a * test_a)

[[ 1.  4.  9.]
 [16. 25. 36.]]


In [37]:
test_matrix=np.array([[1,2,3],[4,5,6]],float)

In [38]:
scalar=5

In [39]:
print(test_matrix + scalar)

[[ 6.  7.  8.]
 [ 9. 10. 11.]]


In [40]:
print(test_matrix - scalar)

[[-4. -3. -2.]
 [-1.  0.  1.]]


In [41]:
print(test_matrix * 5)

[[ 5. 10. 15.]
 [20. 25. 30.]]
